apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2024-06-14T09:15:01Z"
  labels:
    kubernetes.io/metadata.name: kube-public
  name: kube-public
  resourceVersion: "38"
  uid: 26f9aafb-180c-4800-9a69-11acf4058fde
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
