apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-14T05:54:42Z"
  generateName: billing-65f786f4d-
  labels:
    app: billing
    pod-template-hash: 65f786f4d
  name: billing-65f786f4d-pzb6v
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: billing-65f786f4d
    uid: ff162231-fc6b-494b-9875-8db6256a31bd
  resourceVersion: "420556"
  uid: 04e4b6ab-5c4a-4bdc-85f1-cde23131dcd7
spec:
  containers:
  - command:
    - npm
    - run
    - start:dev
    - billing
    env:
    - name: RABBIT_MQ_URI
      value: amqp://192.168.59.102:31005
    - name: RABBIT_MQ_BILLING_QUEUE
      value: billing
    - name: MONGODB_ADVERTISED_HOSTNAME
      value: mongodb-primary
    - name: MONGODB_REPLICA_SET_MODE
      value: primary
    - name: MONGODB_ROOT_PASSWORD
      value: password123
    - name: MONGODB_REPLICA_SET_KEY
      value: replicasetkey123
    image: prakashh16/nestjs-rabbitmq-microservices-main-billing:latest
    imagePullPolicy: Always
    name: billing
    ports:
    - containerPort: 3000
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-77vgz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-77vgz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:50Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:42Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://99d8a327194644126ee15004042d4fdd1ffe199cacd1f55fc51cad8160a6c4d2
    image: prakashh16/nestjs-rabbitmq-microservices-main-billing:latest
    imageID: docker-pullable://prakashh16/nestjs-rabbitmq-microservices-main-billing@sha256:2f6a60e7417adc15d60510c2f93d6789cb40f092d9a1aceb560b7b1a42814d79
    lastState: {}
    name: billing
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-05-14T05:54:49Z"
  hostIP: 192.168.59.102
  hostIPs:
  - ip: 192.168.59.102
  phase: Running
  podIP: 10.244.0.154
  podIPs:
  - ip: 10.244.0.154
  qosClass: Burstable
  startTime: "2024-05-14T05:54:42Z"
