apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-14T05:54:42Z"
  generateName: auth-975544df7-
  labels:
    app: auth
    pod-template-hash: 975544df7
  name: auth-975544df7-vtg9t
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: auth-975544df7
    uid: a54a8aa0-79b9-4f00-ab2a-21bff94be5ab
  resourceVersion: "420544"
  uid: 066c188a-f54c-4f61-a828-cd8341cca27c
spec:
  containers:
  - command:
    - npm
    - run
    - start:dev
    - auth
    env:
    - name: RABBIT_MQ_URI
      value: amqp://192.168.59.102:31005
    - name: RABBIT_MQ_AUTH_QUEUE
      value: auth
    - name: MONGODB_ADVERTISED_HOSTNAME
      value: mongodb-primary
    - name: MONGODB_REPLICA_SET_MODE
      value: primary
    - name: MONGODB_ROOT_PASSWORD
      value: password123
    - name: MONGODB_REPLICA_SET_KEY
      value: replicasetkey123
    image: prakashh16/nestjs-rabbitmq-microservices-main-auth:latest
    imagePullPolicy: Always
    name: auth
    ports:
    - containerPort: 3001
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2d8fh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2d8fh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:46Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:42Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:46Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:46Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-05-14T05:54:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b9f7ee22db400c56478cbf476af1faf9dd8389caf6cafd2f49de8f85d815f190
    image: prakashh16/nestjs-rabbitmq-microservices-main-auth:latest
    imageID: docker-pullable://prakashh16/nestjs-rabbitmq-microservices-main-auth@sha256:9a1e6dfc1ee4b3e77d3a5596233d00e45cc87c308ec49ead2c18613d7152e240
    lastState: {}
    name: auth
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-05-14T05:54:46Z"
  hostIP: 192.168.59.102
  hostIPs:
  - ip: 192.168.59.102
  phase: Running
  podIP: 10.244.0.153
  podIPs:
  - ip: 10.244.0.153
  qosClass: Burstable
  startTime: "2024-05-14T05:54:42Z"
