apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-primary
  template:
    metadata:
      labels:
        app: mongodb-primary
    spec:
      containers:
      - name: mongodb-primary
        image: docker.io/bitnami/mongodb:5.0
        env:
          - name: MONGODB_ADVERTISED_HOSTNAME
            value: mongodb-primary
          - name: MONGODB_REPLICA_SET_MODE
            value: primary
          - name: MONGODB_ROOT_PASSWORD
            value: password123
          - name: MONGODB_REPLICA_SET_KEY
            value: replicasetkey123
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi" 
          requests:
            cpu: "0.1"
            memory: "256Mi" 

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-primary
spec:
  type: NodePort  
  selector:
    app: mongodb-primary
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30000  

