apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-arbiter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-arbiter
  template:
    metadata:
      labels:
        app: mongodb-arbiter
    spec:
      containers:
      - name: mongodb-arbiter
        image: docker.io/bitnami/mongodb:5.0
        env:
        - name: MONGODB_ADVERTISED_HOSTNAME
          value: mongodb-arbiter
        - name: MONGODB_REPLICA_SET_MODE
          value: arbiter
        - name: MONGODB_INITIAL_PRIMARY_HOST
          value: mongodb-primary
        - name: MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
          value: password123
        - name: MONGODB_REPLICA_SET_KEY
          value: replicasetkey123
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "0.1" 
            memory: "256Mi" 
          requests:
            cpu: "0.05" 
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-arbiter
spec:
  type: NodePort  
  selector:
    app: mongodb-arbiter
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30002  