apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-secondary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-secondary
  template:
    metadata:
      labels:
        app: mongodb-secondary
    spec:
      containers:
      - name: mongodb-secondary
        image: docker.io/bitnami/mongodb:5.0
        env:
        - name: MONGODB_ADVERTISED_HOSTNAME
          value: mongodb-secondary
        - name: MONGODB_REPLICA_SET_MODE
          value: secondary
        - name: MONGODB_INITIAL_PRIMARY_HOST
          value: mongodb-primary
        - name: MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD
          value: password123
        - name: MONGODB_REPLICA_SET_KEY
          value: replicasetkey123
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi" 
          requests:
            cpu: "0.1"
            memory: "256Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-secondary
spec:
  type: NodePort  
  selector:
    app: mongodb-secondary
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30004  

